version: 2.1

jobs:
  run-script: # job name
    docker: # Specifies the primary container image,
      - image: cimg/base:2020.01
    steps:
      - run:
        name: Generate invoice
        command: echo $API_TOKEN
    
       
      
